"""empty message

Revision ID: 7755c71eeb5b
Revises: aed83e169515
Create Date: 2022-11-20 15:55:22.473053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7755c71eeb5b'
down_revision = 'aed83e169515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personnel')
    op.drop_table('judges')
    # ### end Alembic commands ###
