"""empty message

Revision ID: d0a036fdb94f
Revises: 7755c71eeb5b
Create Date: 2022-11-28 02:57:23.239229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a036fdb94f'
down_revision = '7755c71eeb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.drop_constraint('FK__professor__user___72C60C4A', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_uuid'], ['uuid'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__professor__user___72C60C4A', 'users', ['user_uuid'], ['uuid'])

    # ### end Alembic commands ###
