USER_DB = "alanp"
PASS_DB = "ALANP"
URL_DB = "DESKTOP-KR0VQA0"
PORT = 1433
NAME_DB = "tkd"
FULL_URL_DB = "mssql+pyodbc://tkd:tkd@DESKTOP-KR0VQA0:1433/tkd?driver=ODBC+Driver+17+for+SQL+Server"
SQLALCHEMY_DATABASE_URI = "mssql+pyodbc://tkd:tkd@DESKTOP-KR0VQA0:1433/tkd?driver=ODBC+Driver+17+for+SQL+Server"
DEBUG = false
BCRYPT_LOG_ROUNDS = 13
SQLALCHEMY_TRACK_MODIFICATIONS = false